#pragma once

#include "types.hpp"
#include <array>
#include <tuple>
#include <format>
#include <algorithm>
#include <string_view>
namespace net { 
 enum class socket_error_code : u16 {
		success                    =     0,
  wsa_invalid_handle         =     6,  /* Specified event object handle is invalid. An application attempts to use an event object, but the specified handle is not valid. */
  wsa_not_enough_memory      =     8,  /* Insufficient memory available. An application used a Windows Sockets function that directly maps to a Windows function. The Windows function is indicating a lack of required memory resources. */
  wsa_invalid_parameter      =    87,  /* One or more parameters are invalid. An application used a Windows Sockets function which directly maps to a Windows function. The Windows function is indicating a problem with one or more parameters. */
  wsa_operation_aborted      =   995,  /* Overlapped operation aborted. An overlapped operation was canceled due to the closure of the socket, or the execution of the SIO_FLUSH command in WSAIoctl (https://learn.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-wsaioctl). */
  wsa_io_incomplete          =   996,  /* Overlapped I/O event object not in signaled state. The application has tried to determine the status of an overlapped operation which is not yet completed. Applications that use WSAGetOverlappedResult (https://learn.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-wsagetoverlappedresult) (with the fWait flag set to FALSE) in a polling mode to determine when an overlapped operation has completed, get this error code until the operation is complete. */
  wsa_io_pending             =   997,  /* Overlapped operations will complete later. The application has initiated an overlapped operation that cannot be completed immediately. A completion indication will be given later when the operation has been completed. */
  wsaeintr                   = 10004, /* Interrupted function call. A blocking operation was interrupted by a call to WSACancelBlockingCall (https://learn.microsoft.com/en-us/windows/desktop/api/winsock2/nf-winsock2-wsacancelblockingcall). */
  wsaebadf                   = 10009, /* File handle is not valid. The file handle supplied is not valid. */
  wsaeacces                  = 10013, /* Permission denied. An attempt was made to access a socket in a way forbidden by its access permissions. An example is using a broadcast address for sendto (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-sendto) without broadcast permission being set using setsockopt (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-setsockopt) (SO_BROADCAST). Another possible reason for the WSAEACCES error is that when the bind function is called (on Windows NT 4.0 with SP4 and later), another application, service, or kernel mode driver is bound to the same address with exclusive access. Such exclusive access is a new feature of Windows NT 4.0 with SP4 and later, and is implemented by using the SO_EXCLUSIVEADDRUSE (https://learn.microsoft.com/en-us/windows/desktop/winsock/so-exclusiveaddruse) option. */
  wsaefault                  = 10014, /* Bad address. The system detected an invalid pointer address in attempting to use a pointer argument of a call. This error occurs if an application passes an invalid pointer value, or if the length of the buffer is too small. For instance, if the length of an argument, which is a sockaddr (https://learn.microsoft.com/en-us/windows/desktop/winsock/sockaddr-2) structure, is smaller than the sizeof(sockaddr). */
  wsaeinval                  = 10022, /* Invalid argument. Some invalid argument was supplied (for example, specifying an invalid level to the setsockopt (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-setsockopt) function). In some instances, it also refers to the current state of the socket—for instance, calling accept (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-accept) on a socket that is not listening. */
  wsaemfile                  = 10024, /* Too many open files. Too many open sockets. Each implementation may have a maximum number of socket handles available, either globally, per process, or per thread. */
  wsaewouldblock             = 10035, /* Resource temporarily unavailable. This error is returned from operations on nonblocking sockets that cannot be completed immediately, for example recv (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-recv) when no data is queued to be read from the socket. It is a nonfatal error, and the operation should be retried later. It is normal for WSAEWOULDBLOCK to be reported as the result from calling connect (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-connect) on a nonblocking SOCK_STREAM socket, since some time must elapse for the connection to be established. */
  wsaeinprogress             = 10036, /* Operation now in progress. A blocking operation is currently executing. Windows Sockets only allows a single blocking operation—per- task or thread—to be outstanding, and if any other function call is made (whether or not it references that or any other socket) the function fails with the WSAEINPROGRESS error. */
  wsaealready                = 10037, /* Operation already in progress. An operation was attempted on a nonblocking socket with an operation already in progress—that is, calling connect (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-connect) a second time on a nonblocking socket that is already connecting, or canceling an asynchronous request (WSAAsyncGetXbyY) that has already been canceled or completed. */
  wsaenotsock                = 10038, /* Socket operation on nonsocket. An operation was attempted on something that is not a socket. Either the socket handle parameter did not reference a valid socket, or for select (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-select), a member of an fd_set was not valid. */
  wsaedestaddrreq            = 10039, /* Destination address required. A required address was omitted from an operation on a socket. For example, this error is returned if sendto (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-sendto) is called with the remote address of ADDR_ANY. */
  wsaemsgsize                = 10040, /* Message too long. A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram was smaller than the datagram itself. */
  wsaeprototype              = 10041, /* Protocol wrong type for socket. A protocol was specified in the socket (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-socket) function call that does not support the semantics of the socket type requested. For example, the ARPA Internet UDP protocol cannot be specified with a socket type of SOCK_STREAM. */
  wsaenoprotoopt             = 10042, /* Bad protocol option. An unknown, invalid or unsupported option or level was specified in a getsockopt (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-getsockopt) or setsockopt (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-setsockopt) call. */    
  wsaeprotonosupport         = 10043, /* Protocol not supported. The requested protocol has not been configured into the system, or no implementation for it exists. For example, a socket (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-socket) call requests a SOCK_DGRAM socket, but specifies a stream protocol. */
  wsaesocktnosupport         = 10044, /* Socket type not supported. The support for the specified socket type does not exist in this address family. For example, the optional type SOCK_RAW might be selected in a socket (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-socket) call, and the implementation does not support SOCK_RAW sockets at all. */
  wsaeoppnotsupp             = 10045, /* Operation not supported. The attempted operation is not supported for the type of object referenced. Usually this occurs when a socket descriptor to a socket that cannot support this operation is trying to accept a connection on a datagram socket. */
  wsaepfnosupport            = 10046, /* Protocol family not supported. The protocol family has not been configured into the system or no implementation for it exists. This message has a slightly different meaning from WSAEAFNOSUPPORT. However, it is interchangeable in most cases, and all Windows Sockets functions that return one of these messages also specify WSAEAFNOSUPPORT. */
  wsaeafnosupport            = 10047, /* Address family not supported by protocol family. An address incompatible with the requested protocol was used. All sockets are created with an associated address family (that is, AF_INET for Internet Protocols) and a generic protocol type (that is, SOCK_STREAM). This error is returned if an incorrect protocol is explicitly requested in the socket (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-socket) call, or if an address of the wrong family is used for a socket, for example, in sendto (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-sendto). */
  wsaeaddrinuse              = 10048, /* Address already in use. Typically, only one usage of each socket address (protocol/IP address/port) is permitted. This error occurs if an application attempts to bind (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-bind) a socket to an IP address/port that has already been used for an existing socket, or a socket that was not closed properly, or one that is still in the process of closing. For server applications that need to bind multiple sockets to the same port number, consider using setsockopt (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-setsockopt) (SO_REUSEADDR). Client applications usually need not call bind at all — connect (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-connect) chooses an unused port automatically. When bind is called with a wildcard address (involving ADDR_ANY), a WSAEADDRINUSE error could be delayed until the specific address is committed. This could happen with a call to another function later, including connect, listen (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-listen), WSAConnect (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-wsaconnect), or WSAJoinLeaf (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-wsajoinleaf). */
  wsaeaddrnotavail           = 10049, /* Cannot assign requested address. The requested address is not valid in its context. This normally results from an attempt to bind (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-bind) to an address that is not valid for the local computer. This can also result from connect (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-connect), sendto (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-sendto), WSAConnect (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-wsaconnect), WSAJoinLeaf (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-wsajoinleaf), or WSASendTo (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-wsasendto) when the remote address or port is not valid for a remote computer (for example, address or port 0). */
  wsaenetdown                = 10050, /* Network is down. A socket operation encountered a dead network. This could indicate a serious failure of the network system (that is, the protocol stack that the Windows Sockets DLL runs over), the network interface, or the local network itself. */
  wsaenetunreach             = 10051, /* Network is unreachable. A socket operation was attempted to an unreachable network. This usually means the local software knows no route to reach the remote host. */
  wsaenetreset               = 10052, /* Network dropped connection on reset. The connection has been broken due to keep-alive activity detecting a failure while the operation was in progress. It can also be returned by setsockopt (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-setsockopt) if an attempt is made to set SO_KEEPALIVE (https://learn.microsoft.com/en-us/windows/desktop/winsock/so-keepalive) on a connection that has already failed. */
  wsaeconnaborted            = 10053, /* Software caused connection abort. An established connection was aborted by the software in your host computer, possibly due to a data transmission time-out or protocol error. */
  wsaeconnreset              = 10054, /* Connection reset by peer. An existing connection was forcibly closed by the remote host. This normally results if the peer application on the remote host is suddenly stopped, the host is rebooted, the host or remote network interface is disabled, or the remote host uses a hard close (see setsockopt (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-setsockopt) for more information on the SO_LINGER option on the remote socket). This error may also result if a connection was broken due to keep-alive activity detecting a failure while one or more operations are in progress. Operations that were in progress fail with WSAENETRESET. Subsequent operations fail with WSAECONNRESET. */
  wsaenobufs                 = 10055, /* No buffer space available. An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full. */
  wsaeisconn                 = 10056, /* Socket is already connected. A connect request was made on an already-connected socket. Some implementations also return this error if sendto (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-sendto) is called on a connected SOCK_DGRAM socket (for SOCK_STREAM sockets, the to parameter in sendto is ignored) although other implementations treat this as a legal occurrence. */
  wsaenotconn                = 10057, /* Socket is not connected. A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using sendto (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-sendto (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-setsockopt))) no address was supplied. Any other type of operation might also return this error—for example, setsockopt (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-setsockopt) setting SO_KEEPALIVE (https://learn.microsoft.com/en-us/windows/desktop/winsock/so-keepalive) if the connection has been reset. */
  wsaeshutdown               = 10058, /* Cannot send after socket shutdown. A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-shutdown) call. By calling shutdown a partial close of a socket is requested, which is a signal that sending or receiving, or both have been discontinued. */
  wsaetoomanyrefs            = 10059, /* Too many references. Too many references to some kernel object. */
  wsaetimedout               = 10060, /* Connection timed out. A connection attempt failed because the connected party did not properly respond after a period of time, or the established connection failed because the connected host has failed to respond. */
  wsaeconnrefused            = 10061, /* Connection refused. No connection could be made because the target computer actively refused it. This usually results from trying to connect to a service that is inactive on the foreign host—that is, one with no server application running. */
  wsaeloop                   = 10062, /* Cannot translate name. Cannot translate a name. */
  wsaenametoolong            = 10063, /* Name too long. A name component or a name was too long. */
  wsaehostdown               = 10064, /* Host is down. A socket operation failed because the destination host is down. A socket operation encountered a dead host. Networking activity on the local host has not been initiated. These conditions are more likely to be indicated by the error WSAETIMEDOUT. */
  wsaehostunreach            = 10065, /* No route to host. A socket operation was attempted to an unreachable host. See WSAENETUNREACH. */
  wsaenotempty               = 10066, /* Directory not empty. Cannot remove a directory that is not empty. */
  wsaeproclim                = 10067, /* Too many processes. A Windows Sockets implementation may have a limit on the number of applications that can use it simultaneously. WSAStartup (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-wsastartup) may fail with this error if the limit has been reached. */
  wsaeusers                  = 10068, /* User quota exceeded. Ran out of user quota. */
  wsaedquot                  = 10069, /* Disk quota exceeded. Ran out of disk quota. */
  wsaestale                  = 10070, /* Stale file handle reference. The file handle reference is no longer available. */
  wsaeremote                 = 10071, /* Item is remote. The item is not available locally. */
  wsasysnotready             = 10091, /* Network subsystem is unavailable. This error is returned by WSAStartup (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-wsastartup) if the Windows Sockets implementation cannot function at this time because the underlying system it uses to provide network services is currently unavailable. Users should check: (1) That the appropriate Windows Sockets DLL file is in the current path. (2) That they are not trying to use more than one Windows Sockets implementation simultaneously. If there is more than one Winsock DLL on your system, be sure the first one in the path is appropriate for the network subsystem currently loaded. (3) The Windows Sockets implementation documentation to be sure all necessary components are currently installed and configured correctly. */
  wsavernotsupported         = 10092, /* Winsock.dll version out of range. The current Windows Sockets implementation does not support the Windows Sockets specification version requested by the application. Check that no old Windows Sockets DLL files are being accessed. */
  wsanotinitialized          = 10093, /* Successful WSAStartup not yet performed. Either the application has not called WSAStartup (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-wsastartup) or WSAStartup failed. The application may be accessing a socket that the current active task does not own (that is, trying to share a socket between tasks), or WSACleanup (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-wsacleanup) has been called too many times. */
  wsaediscon                 = 10101, /* Graceful shutdown in progress. Returned by WSARecv (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-wsarecv) and WSARecvFrom (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-wsarecvfrom) to indicate that the remote party has initiated a graceful shutdown sequence. */
  wsaenomore                 = 10102, /* No more results. No more results can be returned by the WSALookupServiceNext (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-wsalookupservicenexta) function. */
  wsaecancelled              = 10103, /* Call has been canceled. A call to the WSALookupServiceEnd (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-wsalookupserviceend) function was made while this call was still processing. The call has been canceled. */
  wsaeinvalidproctable       = 10104, /* Procedure call table is invalid. The service provider procedure call table is invalid. A service provider returned a bogus procedure table to Ws2_32.dll. This is usually caused by one or more of the function pointers being NULL. */
  wsaeinvalidprovider        = 10105, /* Service provider is invalid. The requested service provider is invalid. This error is returned by the WSCGetProviderInfo (https://learn.microsoft.com/en-us/windows/desktop/api/Ws2spi/nf-ws2spi-wscgetproviderinfo) and WSCGetProviderInfo32 (https://learn.microsoft.com/en-us/windows/desktop/api/Ws2spi/nf-ws2spi-wscgetproviderinfo32) functions if the protocol entry specified could not be found. This error is also returned if the service provider returned a version number other than 2.0. */
  wsaeproviderfailedinit     = 10106, /* Service provider failed to initialize. The requested service provider could not be loaded or initialized. This error is returned if either a service provider's DLL could not be loaded (LoadLibrary (https://learn.microsoft.com/en-us/windows/desktop/api/libloaderapi/nf-libloaderapi-loadlibrarya) failed) or the provider's WSPStartup (https://learn.microsoft.com/en-us/windows/desktop/api/Ws2spi/nf-ws2spi-wspstartup) or NSPStartup (https://learn.microsoft.com/en-us/windows/desktop/api/Ws2spi/nf-ws2spi-nspstartup) function failed. */
  wsasyscallfailure          = 10107, /* System call failure. A system call that should never fail has failed. This is a generic error code, returned under various conditions. Returned when a system call that should never fail does fail. For example, if a call to WaitForMultipleEvents (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-wsawaitformultipleevents) fails or one of the registry functions fails trying to manipulate the protocol/namespace catalogs. Returned when a provider does not return SUCCESS and does not provide an extended error code. Can indicate a service provider implementation error. */
  wsaservice_not_found       = 10108, /* Service not found. No such service is known. The service cannot be found in the specified name space. */
  wsatype_not_found          = 10109, /* Class type not found. The specified class was not found. */
  wsa_e_no_more              = 10110, /* No more results. No more results can be returned by the WSALookupServiceNext (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-wsalookupservicenexta) function. */
  wsa_e_cancelled            = 10111, /* Call was canceled. A call to the WSALookupServiceEnd (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-wsalookupserviceend) function was made while this call was still processing. The call has been canceled. */
  wsaerefused                = 10112, /* Database query was refused. A database query failed because it was actively refused. */
  wsahost_not_found          = 11001, /* Host not found. No such host is known. The name is not an official host name or alias, or it cannot be found in the database(s) being queried. This error may also be returned for protocol and service queries, and means that the specified name could not be found in the relevant database. */
  wsatry_again               = 11002, /* Nonauthoritative host not found. This is usually a temporary error during host name resolution and means that the local server did not receive a response from an authoritative server. A retry at some time later may be successful. */
  wsano_recovery             = 11003, /* This is a nonrecoverable error. This indicates that some sort of nonrecoverable error occurred during a database lookup. This may be because the database files (for example, BSD-compatible HOSTS, SERVICES, or PROTOCOLS files) could not be found, or a DNS request was returned by the server with a severe error. */
  wsano_data                 = 11004, /* Valid name, no data record of requested type. The requested name is valid and was found in the database, but it does not have the correct associated data being resolved for. The usual example for this is a host name-to-address translation attempt (using gethostbyname (https://learn.microsoft.com/en-us/windows/desktop/api/wsipv6ok/nf-wsipv6ok-gethostbyname) or WSAAsyncGetHostByName (https://learn.microsoft.com/en-us/windows/desktop/api/wsipv6ok/nf-wsipv6ok-wsaasyncgethostbyname)) which uses the DNS (Domain Name Server). An MX record is returned but no A record - indicating the host itself exists, but is not directly reachable. */
  wsa_qos_receivers          = 11005, /* QoS receivers. At least one QoS reserve has arrived. */
  wsa_qos_senders            = 11006, /* QoS senders. At least one QoS send path has arrived. */
  wsa_qos_no_senders         = 11007, /* No QoS senders. There are no QoS senders. */
  wsa_qos_no_receivers       = 11008, /* QoS no receivers. There are no QoS receivers. */
  wsa_qos_request_confirmed  = 11009, /* QoS request confirmed. The QoS reserve request has been confirmed. */
  wsa_qos_admission_failure  = 11010, /* QoS admission error. A QoS error occurred due to lack of resources. */
  wsa_qos_policy_failure     = 11011, /* QoS policy failure. The QoS request was rejected because the policy system couldn't allocate the requested resource within the existing policy. */
  wsa_qos_bad_style          = 11012, /* QoS bad style. An unknown or conflicting QoS style was encountered. */
  wsa_qos_bad_object         = 11013, /* QoS bad object. A problem was encountered with some part of the filterspec or the provider-specific buffer in general. */
  wsa_qos_traffic_ctrl_error = 11014, /* QoS traffic control error. An error with the underlying traffic control (TC) API as the generic QoS request was converted for local enforcement by the TC API. This could be due to an out of memory error or to an internal QoS provider error. */
  wsa_qos_generic_error      = 11015, /* QoS generic error. A general QoS error. */
  wsa_qos_eservicetype       = 11016, /* QoS service type error. An invalid or unrecognized service type was found in the QoS flowspec. */
  wsa_qos_eflowspec          = 11017, /* QoS flowspec error. An invalid or inconsistent flowspec was found in the QOS (https://learn.microsoft.com/en-us/windows/win32/api/winsock2/ns-winsock2-qos) structure. */
  wsa_qos_eprovspecbuf       = 11018, /* Invalid QoS provider buffer. An invalid QoS provider-specific buffer. */
  wsa_qos_efilterstyle       = 11019, /* Invalid QoS filter style. An invalid QoS filter style was used. */
  wsa_qos_efiltertype        = 11020, /* Invalid QoS filter type. An invalid QoS filter type was used. */
  wsa_qos_efiltercount       = 11021, /* Incorrect QoS filter count. An incorrect number of QoS FILTERSPECs were specified in the FLOWDESCRIPTOR. */
  wsa_qos_eobjlength         = 11022, /* Invalid QoS object length. An object with an invalid ObjectLength field was specified in the QoS provider-specific buffer. */
  wsa_qos_eflowcount         = 11023, /* Incorrect QoS flow count. An incorrect number of flow descriptors was specified in the QoS structure. */
  wsa_qos_eunknownpsobj      = 11024, /* Unrecognized QoS object. An unrecognized object was found in the QoS provider-specific buffer. */
  wsa_qos_epolicyobj         = 11025, /* Invalid QoS policy object. An invalid policy object was found in the QoS provider-specific buffer. */
  wsa_qos_eflowdesc          = 11026, /* Invalid QoS flow descriptor. An invalid QoS flow descriptor was found in the flow descriptor list. */
  wsa_qos_epsflowspec        = 11027, /* Invalid QoS provider-specific flowspec. An invalid or inconsistent flowspec was found in the QoS provider-specific buffer. */
  wsa_qos_epsfilterspec      = 11028, /* Invalid QoS provider-specific filterspec. An invalid FILTERSPEC was found in the QoS provider-specific buffer. */
  wsa_qos_esdmodeobj         = 11029, /* Invalid QoS shape discard mode object. An invalid shape discard mode object was found in the QoS provider-specific buffer. */
  wsa_qos_eshaperateobj      = 11030, /* Invalid QoS shaping rate object. An invalid shaping rate object was found in the QoS provider-specific buffer. */
  wsa_qos_reserved_petype    = 11031, /* Reserved policy QoS element type. A reserved policy element was found in the QoS provider-specific buffer. */
 };

 inline constexpr std::array<std::pair<socket_error_code, std::string_view>, 96> SOCKET_ERROR_CODE_LOOKUP {
		std::pair<socket_error_code, std::string_view>{ socket_error_code::success,                    "socket_error_code::success" },
  std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_invalid_handle,         "socket_error_code::wsa_invalid_handle" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_not_enough_memory,      "socket_error_code::wsa_not_enough_memory" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_invalid_parameter,      "socket_error_code::wsa_invalid_parameter" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_operation_aborted,      "socket_error_code::wsa_operation_aborted" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_io_incomplete,          "socket_error_code::wsa_io_incomplete" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_io_pending,             "socket_error_code::wsa_io_pending" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeintr,                   "socket_error_code::wsaeintr" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaebadf,                   "socket_error_code::wsaebadf" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeacces,                  "socket_error_code::wsaeacces" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaefault,                  "socket_error_code::wsaefault" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeinval,                  "socket_error_code::wsaeinval" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaemfile,                  "socket_error_code::wsaemfile" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaewouldblock,             "socket_error_code::wsaewouldblock" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeinprogress,             "socket_error_code::wsaeinprogress" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaealready,                "socket_error_code::wsaealready" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaenotsock,                "socket_error_code::wsaenotsock" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaedestaddrreq,            "socket_error_code::wsaedestaddrreq" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaemsgsize,                "socket_error_code::wsaemsgsize" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeprototype,              "socket_error_code::wsaeprototype" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaenoprotoopt,             "socket_error_code::wsaenoprotoopt" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeprotonosupport,         "socket_error_code::wsaeprotonosupport" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaesocktnosupport,         "socket_error_code::wsaesocktnosupport" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeoppnotsupp,             "socket_error_code::wsaeoppnotsupp" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaepfnosupport,            "socket_error_code::wsaepfnosupport" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeafnosupport,            "socket_error_code::wsaeafnosupport" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeaddrinuse,              "socket_error_code::wsaeaddrinuse" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeaddrnotavail,           "socket_error_code::wsaeaddrnotavail" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaenetdown,                "socket_error_code::wsaenetdown" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaenetunreach,             "socket_error_code::wsaenetunreach" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaenetreset,               "socket_error_code::wsaenetreset" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeconnaborted,            "socket_error_code::wsaeconnaborted" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeconnreset,              "socket_error_code::wsaeconnreset" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaenobufs,                 "socket_error_code::wsaenobufs" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeisconn,                 "socket_error_code::wsaeisconn" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaenotconn,                "socket_error_code::wsaenotconn" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeshutdown,               "socket_error_code::wsaeshutdown" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaetoomanyrefs,            "socket_error_code::wsaetoomanyrefs" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaetimedout,               "socket_error_code::wsaetimedout" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeconnrefused,            "socket_error_code::wsaeconnrefused" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeloop,                   "socket_error_code::wsaeloop" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaenametoolong,            "socket_error_code::wsaenametoolong" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaehostdown,               "socket_error_code::wsaehostdown" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaehostunreach,            "socket_error_code::wsaehostunreach" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaenotempty,               "socket_error_code::wsaenotempty" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeproclim,                "socket_error_code::wsaeproclim" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeusers,                  "socket_error_code::wsaeusers" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaedquot,                  "socket_error_code::wsaedquot" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaestale,                  "socket_error_code::wsaestale" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeremote,                 "socket_error_code::wsaeremote" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsasysnotready,             "socket_error_code::wsasysnotready" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsavernotsupported,         "socket_error_code::wsavernotsupported" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsanotinitialized,          "socket_error_code::wsanotinitialized" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaediscon,                 "socket_error_code::wsaediscon" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaenomore,                 "socket_error_code::wsaenomore" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaecancelled,              "socket_error_code::wsaecancelled" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeinvalidproctable,       "socket_error_code::wsaeinvalidproctable" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeinvalidprovider,        "socket_error_code::wsaeinvalidprovider" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeproviderfailedinit,     "socket_error_code::wsaeproviderfailedinit" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsasyscallfailure,          "socket_error_code::wsasyscallfailure" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaservice_not_found,       "socket_error_code::wsaservice_not_found" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsatype_not_found,          "socket_error_code::wsatype_not_found" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_e_no_more,              "socket_error_code::wsa_e_no_more" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_e_cancelled,            "socket_error_code::wsa_e_cancelled" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaerefused,                "socket_error_code::wsaerefused" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsahost_not_found,          "socket_error_code::wsahost_not_found" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsatry_again,               "socket_error_code::wsatry_again" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsano_recovery,             "socket_error_code::wsano_recovery" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsano_data,                 "socket_error_code::wsano_data" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_receivers,          "socket_error_code::wsa_qos_receivers" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_senders,            "socket_error_code::wsa_qos_senders" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_no_senders,         "socket_error_code::wsa_qos_no_senders" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_no_receivers,       "socket_error_code::wsa_qos_no_receivers" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_request_confirmed,  "socket_error_code::wsa_qos_request_confirmed" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_admission_failure,  "socket_error_code::wsa_qos_admission_failure" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_policy_failure,     "socket_error_code::wsa_qos_policy_failure" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_bad_style,          "socket_error_code::wsa_qos_bad_style" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_bad_object,         "socket_error_code::wsa_qos_bad_object" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_traffic_ctrl_error, "socket_error_code::wsa_qos_traffic_ctrl_error" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_generic_error,      "socket_error_code::wsa_qos_generic_error" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_eservicetype,       "socket_error_code::wsa_qos_eservicetype" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_eflowspec,          "socket_error_code::wsa_qos_eflowspec" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_eprovspecbuf,       "socket_error_code::wsa_qos_eprovspecbuf" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_efilterstyle,       "socket_error_code::wsa_qos_efilterstyle" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_efiltertype,        "socket_error_code::wsa_qos_efiltertype" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_efiltercount,       "socket_error_code::wsa_qos_efiltercount" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_eobjlength,         "socket_error_code::wsa_qos_eobjlength" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_eflowcount,         "socket_error_code::wsa_qos_eflowcount" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_eunknownpsobj,      "socket_error_code::wsa_qos_eunknownpsobj" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_epolicyobj,         "socket_error_code::wsa_qos_epolicyobj" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_eflowdesc,          "socket_error_code::wsa_qos_eflowdesc" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_epsflowspec,        "socket_error_code::wsa_qos_epsflowspec" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_epsfilterspec,      "socket_error_code::wsa_qos_epsfilterspec" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_esdmodeobj,         "socket_error_code::wsa_qos_esdmodeobj" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_eshaperateobj,      "socket_error_code::wsa_qos_eshaperateobj" },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_reserved_petype,    "socket_error_code::wsa_qos_reserved_petype" }
 };

 inline constexpr std::array<std::pair<socket_error_code, std::string_view>, 96> SOCKET_ERROR_CODE_DESCRIPTION_LOOKUP{
		std::pair<socket_error_code, std::string_view>{ socket_error_code::success,                    "" },
  std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_invalid_handle,         "Specified event object handle is invalid. An application attempts to use an event object but the specified handle is not valid." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_not_enough_memory,      "Insufficient memory available. An application used a Windows Sockets function that directly maps to a Windows function. The Windows function is indicating a lack of required memory resources." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_invalid_parameter,      "One or more parameters are invalid. An application used a Windows Sockets function which directly maps to a Windows function. The Windows function is indicating a problem with one or more parameters." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_operation_aborted,      "Overlapped operation aborted. An overlapped operation was canceled due to the closure of the socket or the execution of the SIO_FLUSH command in WSAIoctl (https://learn.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-wsaioctl)." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_io_incomplete,          "Overlapped I/O event object not in signaled state. The application has tried to determine the status of an overlapped operation which is not yet completed. Applications that use WSAGetOverlappedResult (https://learn.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-wsagetoverlappedresult) (with the fWait flag set to FALSE) in a polling mode to determine when an overlapped operation has completed get this error code until the operation is complete." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_io_pending,             "Overlapped operations will complete later. The application has initiated an overlapped operation that cannot be completed immediately. A completion indication will be given later when the operation has been completed." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeintr,                   "Interrupted function call. A blocking operation was interrupted by a call to WSACancelBlockingCall (https://learn.microsoft.com/en-us/windows/desktop/api/winsock2/nf-winsock2-wsacancelblockingcall)." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaebadf,                   "File handle is not valid. The file handle supplied is not valid." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeacces,                  "Permission denied. An attempt was made to access a socket in a way forbidden by its access permissions. An example is using a broadcast address for sendto (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-sendto) without broadcast permission being set using setsockopt (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-setsockopt) (SO_BROADCAST). Another possible reason for the WSAEACCES error is that when the bind function is called (on Windows NT 4.0 with SP4 and later) another application service or kernel mode driver is bound to the same address with exclusive access. Such exclusive access is a new feature of Windows NT 4.0 with SP4 and later and is implemented by using the SO_EXCLUSIVEADDRUSE (https://learn.microsoft.com/en-us/windows/desktop/winsock/so-exclusiveaddruse) option." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaefault,                  "Bad address. The system detected an invalid pointer address in attempting to use a pointer argument of a call. This error occurs if an application passes an invalid pointer value or if the length of the buffer is too small. For instance if the length of an argument which is a sockaddr (https://learn.microsoft.com/en-us/windows/desktop/winsock/sockaddr-2) structure is smaller than the sizeof(sockaddr)." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeinval,                  "Invalid argument. Some invalid argument was supplied (for example specifying an invalid level to the setsockopt (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-setsockopt) function). In some instances it also refers to the current state of the socket—for instance calling accept (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-accept) on a socket that is not listening." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaemfile,                  "Too many open files. Too many open sockets. Each implementation may have a maximum number of socket handles available either globally per process or per thread." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaewouldblock,             "Resource temporarily unavailable. This error is returned from operations on nonblocking sockets that cannot be completed immediately for example recv (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-recv) when no data is queued to be read from the socket. It is a nonfatal error and the operation should be retried later. It is normal for WSAEWOULDBLOCK to be reported as the result from calling connect (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-connect) on a nonblocking SOCK_STREAM socket since some time must elapse for the connection to be established." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeinprogress,             "Operation now in progress. A blocking operation is currently executing. Windows Sockets only allows a single blocking operation—per- task or thread—to be outstanding and if any other function call is made (whether or not it references that or any other socket) the function fails with the WSAEINPROGRESS error." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaealready,                "Operation already in progress. An operation was attempted on a nonblocking socket with an operation already in progress—that is calling connect (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-connect) a second time on a nonblocking socket that is already connecting or canceling an asynchronous request (WSAAsyncGetXbyY) that has already been canceled or completed." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaenotsock,                "Socket operation on nonsocket. An operation was attempted on something that is not a socket. Either the socket handle parameter did not reference a valid socket or for select (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-select) a member of an fd_set was not valid." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaedestaddrreq,            "Destination address required. A required address was omitted from an operation on a socket. For example this error is returned if sendto (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-sendto) is called with the remote address of ADDR_ANY." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaemsgsize,                "Message too long. A message sent on a datagram socket was larger than the internal message buffer or some other network limit or the buffer used to receive a datagram was smaller than the datagram itself." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeprototype,              "Protocol wrong type for socket. A protocol was specified in the socket (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-socket) function call that does not support the semantics of the socket type requested. For example the ARPA Internet UDP protocol cannot be specified with a socket type of SOCK_STREAM." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaenoprotoopt,             "Bad protocol option. An unknown invalid or unsupported option or level was specified in a getsockopt (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-getsockopt) or setsockopt (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-setsockopt) call. */ " },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeprotonosupport,         "Protocol not supported. The requested protocol has not been configured into the system or no implementation for it exists. For example a socket (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-socket) call requests a SOCK_DGRAM socket but specifies a stream protocol." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaesocktnosupport,         "Socket type not supported. The support for the specified socket type does not exist in this address family. For example the optional type SOCK_RAW might be selected in a socket (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-socket) call and the implementation does not support SOCK_RAW sockets at all." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeoppnotsupp,             "Operation not supported. The attempted operation is not supported for the type of object referenced. Usually this occurs when a socket descriptor to a socket that cannot support this operation is trying to accept a connection on a datagram socket." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaepfnosupport,            "Protocol family not supported. The protocol family has not been configured into the system or no implementation for it exists. This message has a slightly different meaning from WSAEAFNOSUPPORT. However it is interchangeable in most cases and all Windows Sockets functions that return one of these messages also specify WSAEAFNOSUPPORT." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeafnosupport,            "Address family not supported by protocol family. An address incompatible with the requested protocol was used. All sockets are created with an associated address family (that is AF_INET for Internet Protocols) and a generic protocol type (that is SOCK_STREAM). This error is returned if an incorrect protocol is explicitly requested in the socket (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-socket) call or if an address of the wrong family is used for a socket for example in sendto (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-sendto)." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeaddrinuse,              "Address already in use. Typically only one usage of each socket address (protocol/IP address/port) is permitted. This error occurs if an application attempts to bind (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-bind) a socket to an IP address/port that has already been used for an existing socket or a socket that was not closed properly or one that is still in the process of closing. For server applications that need to bind multiple sockets to the same port number consider using setsockopt (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-setsockopt) (SO_REUSEADDR). Client applications usually need not call bind at all — connect (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-connect) chooses an unused port automatically. When bind is called with a wildcard address (involving ADDR_ANY) a WSAEADDRINUSE error could be delayed until the specific address is committed. This could happen with a call to another function later including connect listen (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-listen) WSAConnect (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-wsaconnect) or WSAJoinLeaf (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-wsajoinleaf)." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeaddrnotavail,           "Cannot assign requested address. The requested address is not valid in its context. This normally results from an attempt to bind (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-bind) to an address that is not valid for the local computer. This can also result from connect (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-connect) sendto (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-sendto) WSAConnect (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-wsaconnect) WSAJoinLeaf (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-wsajoinleaf) or WSASendTo (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-wsasendto) when the remote address or port is not valid for a remote computer (for example address or port 0)." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaenetdown,                "Network is down. A socket operation encountered a dead network. This could indicate a serious failure of the network system (that is the protocol stack that the Windows Sockets DLL runs over) the network interface or the local network itself." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaenetunreach,             "Network is unreachable. A socket operation was attempted to an unreachable network. This usually means the local software knows no route to reach the remote host." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaenetreset,               "Network dropped connection on reset. The connection has been broken due to keep-alive activity detecting a failure while the operation was in progress. It can also be returned by setsockopt (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-setsockopt) if an attempt is made to set SO_KEEPALIVE (https://learn.microsoft.com/en-us/windows/desktop/winsock/so-keepalive) on a connection that has already failed." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeconnaborted,            "Software caused connection abort. An established connection was aborted by the software in your host computer possibly due to a data transmission time-out or protocol error." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeconnreset,              "Connection reset by peer. An existing connection was forcibly closed by the remote host. This normally results if the peer application on the remote host is suddenly stopped the host is rebooted the host or remote network interface is disabled or the remote host uses a hard close (see setsockopt (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-setsockopt) for more information on the SO_LINGER option on the remote socket). This error may also result if a connection was broken due to keep-alive activity detecting a failure while one or more operations are in progress. Operations that were in progress fail with WSAENETRESET. Subsequent operations fail with WSAECONNRESET." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaenobufs,                 "No buffer space available. An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeisconn,                 "Socket is already connected. A connect request was made on an already-connected socket. Some implementations also return this error if sendto (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-sendto) is called on a connected SOCK_DGRAM socket (for SOCK_STREAM sockets the to parameter in sendto is ignored) although other implementations treat this as a legal occurrence." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaenotconn,                "Socket is not connected. A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using sendto (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-sendto (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-setsockopt))) no address was supplied. Any other type of operation might also return this error—for example setsockopt (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-setsockopt) setting SO_KEEPALIVE (https://learn.microsoft.com/en-us/windows/desktop/winsock/so-keepalive) if the connection has been reset." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeshutdown,               "Cannot send after socket shutdown. A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-shutdown) call. By calling shutdown a partial close of a socket is requested which is a signal that sending or receiving or both have been discontinued." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaetoomanyrefs,            "Too many references. Too many references to some kernel object." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaetimedout,               "Connection timed out. A connection attempt failed because the connected party did not properly respond after a period of time or the established connection failed because the connected host has failed to respond." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeconnrefused,            "Connection refused. No connection could be made because the target computer actively refused it. This usually results from trying to connect to a service that is inactive on the foreign host—that is one with no server application running." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeloop,                   "Cannot translate name. Cannot translate a name." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaenametoolong,            "Name too long. A name component or a name was too long." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaehostdown,               "Host is down. A socket operation failed because the destination host is down. A socket operation encountered a dead host. Networking activity on the local host has not been initiated. These conditions are more likely to be indicated by the error WSAETIMEDOUT." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaehostunreach,            "No route to host. A socket operation was attempted to an unreachable host. See WSAENETUNREACH." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaenotempty,               "Directory not empty. Cannot remove a directory that is not empty." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeproclim,                "Too many processes. A Windows Sockets implementation may have a limit on the number of applications that can use it simultaneously. WSAStartup (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-wsastartup) may fail with this error if the limit has been reached." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeusers,                  "User quota exceeded. Ran out of user quota." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaedquot,                  "Disk quota exceeded. Ran out of disk quota." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaestale,                  "Stale file handle reference. The file handle reference is no longer available." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeremote,                 "Item is remote. The item is not available locally." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsasysnotready,             "Network subsystem is unavailable. This error is returned by WSAStartup (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-wsastartup) if the Windows Sockets implementation cannot function at this time because the underlying system it uses to provide network services is currently unavailable. Users should check: (1) That the appropriate Windows Sockets DLL file is in the current path. (2) That they are not trying to use more than one Windows Sockets implementation simultaneously. If there is more than one Winsock DLL on your system be sure the first one in the path is appropriate for the network subsystem currently loaded. (3) The Windows Sockets implementation documentation to be sure all necessary components are currently installed and configured correctly." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsavernotsupported,         "Winsock.dll version out of range. The current Windows Sockets implementation does not support the Windows Sockets specification version requested by the application. Check that no old Windows Sockets DLL files are being accessed." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsanotinitialized,          "Successful WSAStartup not yet performed. Either the application has not called WSAStartup (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-wsastartup) or WSAStartup failed. The application may be accessing a socket that the current active task does not own (that is trying to share a socket between tasks) or WSACleanup (https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-wsacleanup) has been called too many times." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaediscon,                 "Graceful shutdown in progress. Returned by WSARecv (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-wsarecv) and WSARecvFrom (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-wsarecvfrom) to indicate that the remote party has initiated a graceful shutdown sequence." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaenomore,                 "No more results. No more results can be returned by the WSALookupServiceNext (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-wsalookupservicenexta) function." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaecancelled,              "Call has been canceled. A call to the WSALookupServiceEnd (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-wsalookupserviceend) function was made while this call was still processing. The call has been canceled." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeinvalidproctable,       "Procedure call table is invalid. The service provider procedure call table is invalid. A service provider returned a bogus procedure table to Ws2_32.dll. This is usually caused by one or more of the function pointers being NULL." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeinvalidprovider,        "Service provider is invalid. The requested service provider is invalid. This error is returned by the WSCGetProviderInfo (https://learn.microsoft.com/en-us/windows/desktop/api/Ws2spi/nf-ws2spi-wscgetproviderinfo) and WSCGetProviderInfo32 (https://learn.microsoft.com/en-us/windows/desktop/api/Ws2spi/nf-ws2spi-wscgetproviderinfo32) functions if the protocol entry specified could not be found. This error is also returned if the service provider returned a version number other than 2.0." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaeproviderfailedinit,     "Service provider failed to initialize. The requested service provider could not be loaded or initialized. This error is returned if either a service provider's DLL could not be loaded (LoadLibrary (https://learn.microsoft.com/en-us/windows/desktop/api/libloaderapi/nf-libloaderapi-loadlibrarya) failed) or the provider's WSPStartup (https://learn.microsoft.com/en-us/windows/desktop/api/Ws2spi/nf-ws2spi-wspstartup) or NSPStartup (https://learn.microsoft.com/en-us/windows/desktop/api/Ws2spi/nf-ws2spi-nspstartup) function failed." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsasyscallfailure,          "System call failure. A system call that should never fail has failed. This is a generic error code returned under various conditions. Returned when a system call that should never fail does fail. For example if a call to WaitForMultipleEvents (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-wsawaitformultipleevents) fails or one of the registry functions fails trying to manipulate the protocol/namespace catalogs. Returned when a provider does not return SUCCESS and does not provide an extended error code. Can indicate a service provider implementation error." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaservice_not_found,       "Service not found. No such service is known. The service cannot be found in the specified name space." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsatype_not_found,          "Class type not found. The specified class was not found." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_e_no_more,              "No more results. No more results can be returned by the WSALookupServiceNext (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-wsalookupservicenexta) function." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_e_cancelled,            "Call was canceled. A call to the WSALookupServiceEnd (https://learn.microsoft.com/en-us/windows/desktop/api/Winsock2/nf-winsock2-wsalookupserviceend) function was made while this call was still processing. The call has been canceled." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsaerefused,                "Database query was refused. A database query failed because it was actively refused." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsahost_not_found,          "Host not found. No such host is known. The name is not an official host name or alias or it cannot be found in the database(s) being queried. This error may also be returned for protocol and service queries and means that the specified name could not be found in the relevant database." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsatry_again,               "Nonauthoritative host not found. This is usually a temporary error during host name resolution and means that the local server did not receive a response from an authoritative server. A retry at some time later may be successful." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsano_recovery,             "This is a nonrecoverable error. This indicates that some sort of nonrecoverable error occurred during a database lookup. This may be because the database files (for example BSD-compatible HOSTS SERVICES or PROTOCOLS files) could not be found or a DNS request was returned by the server with a severe error." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsano_data,                 "Valid name no data record of requested type. The requested name is valid and was found in the database but it does not have the correct associated data being resolved for. The usual example for this is a host name-to-address translation attempt (using gethostbyname (https://learn.microsoft.com/en-us/windows/desktop/api/wsipv6ok/nf-wsipv6ok-gethostbyname) or WSAAsyncGetHostByName (https://learn.microsoft.com/en-us/windows/desktop/api/wsipv6ok/nf-wsipv6ok-wsaasyncgethostbyname)) which uses the DNS (Domain Name Server). An MX record is returned but no A record - indicating the host itself exists but is not directly reachable." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_receivers,          "QoS receivers. At least one QoS reserve has arrived." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_senders,            "QoS senders. At least one QoS send path has arrived." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_no_senders,         "No QoS senders. There are no QoS senders." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_no_receivers,       "QoS no receivers. There are no QoS receivers." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_request_confirmed,  "QoS request confirmed. The QoS reserve request has been confirmed." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_admission_failure,  "QoS admission error. A QoS error occurred due to lack of resources." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_policy_failure,     "QoS policy failure. The QoS request was rejected because the policy system couldn't allocate the requested resource within the existing policy." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_bad_style,          "QoS bad style. An unknown or conflicting QoS style was encountered." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_bad_object,         "QoS bad object. A problem was encountered with some part of the filterspec or the provider-specific buffer in general." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_traffic_ctrl_error, "QoS traffic control error. An error with the underlying traffic control (TC) API as the generic QoS request was converted for local enforcement by the TC API. This could be due to an out of memory error or to an internal QoS provider error." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_generic_error,      "QoS generic error. A general QoS error." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_eservicetype,       "QoS service type error. An invalid or unrecognized service type was found in the QoS flowspec." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_eflowspec,          "QoS flowspec error. An invalid or inconsistent flowspec was found in the QOS (https://learn.microsoft.com/en-us/windows/win32/api/winsock2/ns-winsock2-qos) structure." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_eprovspecbuf,       "Invalid QoS provider buffer. An invalid QoS provider-specific buffer." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_efilterstyle,       "Invalid QoS filter style. An invalid QoS filter style was used." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_efiltertype,        "Invalid QoS filter type. An invalid QoS filter type was used." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_efiltercount,       "Incorrect QoS filter count. An incorrect number of QoS FILTERSPECs were specified in the FLOWDESCRIPTOR." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_eobjlength,         "Invalid QoS object length. An object with an invalid ObjectLength field was specified in the QoS provider-specific buffer." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_eflowcount,         "Incorrect QoS flow count. An incorrect number of flow descriptors was specified in the QoS structure." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_eunknownpsobj,      "Unrecognized QoS object. An unrecognized object was found in the QoS provider-specific buffer." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_epolicyobj,         "Invalid QoS policy object. An invalid policy object was found in the QoS provider-specific buffer." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_eflowdesc,          "Invalid QoS flow descriptor. An invalid QoS flow descriptor was found in the flow descriptor list." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_epsflowspec,        "Invalid QoS provider-specific flowspec. An invalid or inconsistent flowspec was found in the QoS provider-specific buffer." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_epsfilterspec,      "Invalid QoS provider-specific filterspec. An invalid FILTERSPEC was found in the QoS provider-specific buffer." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_esdmodeobj,         "Invalid QoS shape discard mode object. An invalid shape discard mode object was found in the QoS provider-specific buffer." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_eshaperateobj,      "Invalid QoS shaping rate object. An invalid shaping rate object was found in the QoS provider-specific buffer." },
		std::pair<socket_error_code, std::string_view>{ socket_error_code::wsa_qos_reserved_petype,    "Reserved policy QoS element type. A reserved policy element was found in the QoS provider-specific buffer." }
 };

 [[nodiscard]] inline constexpr std::string_view lookup_enum(socket_error_code const socket_error_code) noexcept {
  auto const it = std::find_if(std::cbegin(SOCKET_ERROR_CODE_LOOKUP), std::cend(SOCKET_ERROR_CODE_LOOKUP), [&socket_error_code] (auto const entry) { return entry.first == socket_error_code; });
  if (it == std::cend(SOCKET_ERROR_CODE_LOOKUP)) [[unlikely]] {
   return "Invalid Enum";
  } else [[likely]] {
   return it->second;
  }
 }
 [[nodiscard]] inline constexpr std::string_view lookup_enum_description(socket_error_code const socket_error_code) noexcept {
  auto const it = std::find_if(std::cbegin(SOCKET_ERROR_CODE_DESCRIPTION_LOOKUP), std::cend(SOCKET_ERROR_CODE_DESCRIPTION_LOOKUP), [&socket_error_code] (auto const entry) { return entry.first == socket_error_code; });
  if (it == std::cend(SOCKET_ERROR_CODE_DESCRIPTION_LOOKUP)) [[unlikely]] {
   return "Invalid Enum";
  } else [[likely]] {
   return it->second;
  }
 }
 [[nodiscard]] inline constexpr std::string lookup_enum_verbose(socket_error_code const socket_error_code) noexcept {
  auto const it = std::find_if(std::cbegin(SOCKET_ERROR_CODE_LOOKUP), std::cend(SOCKET_ERROR_CODE_LOOKUP), [&socket_error_code] (auto const entry) { return entry.first == socket_error_code; });
  if (it == std::cend(SOCKET_ERROR_CODE_LOOKUP)) [[unlikely]] {
   return "Invalid Enum";
  } else [[likely]] {
   return std::format("{}: {}", it->second, SOCKET_ERROR_CODE_DESCRIPTION_LOOKUP[it - std::cbegin(SOCKET_ERROR_CODE_LOOKUP)].second);
  }
 }
}
